<?php
namespace App\Constants;
class Constants
{
  const SESSION_KEY_USER = 'session_key_user';
  const RESPONSE_STATUS_SUCCESS = 'success';
  const RESPONSE_STATUS_ERROR = 'error';
  const RESPONSE_STATUS_ACCESS_IS_DENIED = 'access is denied';
  const RESPONSE_MESSAGE_INVALID_USER = 'Invalid email or password';
  const RESPONSE_STATUS_USER_NOTFOUND = 'User not exist';
  const RESPONSE_STATUS_HCF_NOTFOUND = 'Hfc not found';
  const RESPONSE_MESSAGE_EMAIL_EXISTED = 'Email existed';
  const RESPONSE_MESSAGE_CLINIC_NOTFOUND = 'Clinic not found';
  const RESPONSE_MESSAGE_LOCATION_NOTFOUND = 'Health care facility location not found';
  const RESPONSE_MESSAGE_NOT_ENOUGH_TOKEN = 'Not enough token';
  const RESPONSE_MESSAGE_REWARD_IS_OWNED = 'Reward is owned';
  const RESPONSE_MESSAGE_REWARD_NOTFOUND = 'Reward not found';
  const RESPONSE_MESSAGE_REWARD_NOTOWNED = 'Reward not owned';
  const RESPONSE_MESSAGE_INVALID_EMAIL_FORMAT = 'Invalid email format';
  const RESPONSE_MESSAGE_EMAIL_NOTFOUND = 'Email not found';
  const RESPONSE_MESSAGE_LINK_WAS_BE_USED = 'Reset password link was be used';
  const RESPONSE_MESSAGE_USER_NOTFOUND = 'User not found';
  const RESPONSE_MESSAGE_INVALID_INPUT = 'Invalid input';
  const RESPONSE_MESSAGE_BENEFIT_EXITED = 'Benefit existed';
  const RESPONSE_MESSAGE_INVALID_PASSWORD = 'Invalid password';
  const RESPONSE_STATUS_NUMBER_NOTFOUND = 'Phone number not existed';
  const RESPONSE_MESSAGE_PHARMACY_NOTFOUND = 'Pharmacy not found';
  const RESPONSE_MESSAGE_PASSWORD_NOT_ENOUGH_LENGTH = 'Password have to at least 6 characters';
  const RESPONSE_MESSAGE_FAQ_NOT_FOUND = 'FAQ not found';
  const RESPONSE_MESSAGE_FILE_NOT_SUPPORTED = 'This file type is not supported';
  const REPORT_MANAGER = 4;
  const HOSPITAL_ADMIN = 3;
  const SUPER_ADMIN = 2;
  const ADMIN = 1;
  const USER = 0;
  const DEFAULT_AVATAR = 29;
  const DEFAULT_BACKGROUND = 58;
  const WEB_LINK = 'http://docandi.qa.pgtest.co:2016/';
  const API_URL = 'http://docandi2.qa.pgtest.co:2016/';
    const OVERVIEW_VIDEO_URL = Constants::API_URL.'videos/DocandI.mp4';
  const LOGIN_PAGE_LINK = Constants::WEB_LINK.'login?email=';
  const DESTINATION_LINK = Constants::WEB_LINK.'ResetPassword?token=';
  const MY_EMAIL = 'noah@docandi.com';
  const IMAGES_URL = Constants::API_URL.'images/';
  const IMAGE_SMS_LINK = Constants::API_URL.'images/discount_card_modified/';
  const CLINIC_IMAGE_URL = 'clinics/';
  const CLINIC_UPLOAD_IMAGE = 'images/clinics';
  const IMAGES = 'images/';
  const PHARMACY_IMAGE_URL = 'pharmacy_logos/';
  const PHARMACY_UPLOAD_IMAGE = 'images/pharmacy_logos';
  const HCF_IMAGE_URL = 'hospital/';
  const HCF_UPLOAD_IMAGE = 'images/hospital';
  const SAVING_CART_URL = 'images/saving_card';
  const SAVING_CART_MODIFIED = 'saving_card_modified';
  const SAVING_CART_MODIFIED_URL = 'images/saving_card_modified';
  const DIS_COUNT_CARD = 'discount_card/';
  const DIS_COUNT_CARD_URL = 'images/discount_card';
  const DIS_COUNT_CARD_MODIFIED = 'discount_card_modified';
  const DIS_COUNT_CARD_MODIFIED_URL = 'images/discount_card_modified';
  const PDF_FILE_URL = 'pdfs/';
  const REPORT_UPLOAD_URL = 'report_upload/';
  const CHECK_ONLINE_TIME = 65;
  const AVATAR = 1;
  const SAVING_MONEY_USED = 62;
  const LIMIT_PHARMACY = 10;
  const BACKGROUND = 2;
  const IS_USING_340B = 100;
  const SELECT_PHARMACY = 150;
  const INFORMED_BENEFITS = 100;
  const SUBMIT_USING = 100;
  const IS_NOT_USING_340B = 25;
  const INFORMED_PHARMACY_LOCATION =50;
  const NEXT_SUBMIT = 25;
  const AGREE_TO_CHANGE = 100;
  const ALERTED_DOCTOR = 50;
  const TOLD_FREEDOM_CHOICE = 100;
  const SUMIT_CHANGE = 200;
  const NOT_AGREE_TO_CHANGE = 50;
  const SELECTED_REASON = 50;
  const SUBMIT_NOT_CHANGE = 50;
  const SAVING_MONEY_CHANGE = 62;
  const TOKEN_COST = 20000;
  const DEFAULT_TOKEN = 0;
  const RXGRP = 'A';
  const INPUT_CODE = 'AHSFH';
  const DISCOUNT_CARD_DEFAULT_LOGO = 'discount_card/ahs_dcc_image.png';

  const TEST_ACCOUNT_SID = 'AC109270fb493e0746998997f6ecab6a07';
  const TEST_AUTHTOKEN = 'de971edbc08a682ca79b4bb652dd612f';
  const SEND_SMS_PHONE_NUMBER = '+17087628299';
  const FROM_EMAIL = 'info@docandi.com';
  const DEFAULT_PASSWORD = 'docandi2018';
  const GEO_API_KEY = 'AIzaSyC-KKjJS8iWRJsnJPiBsHCa8Juzb_PBU8I';
}
?>